export const GET_LAUNDRY_FLOORS = 'get_laundry_floors'
export const SHOW_TOAST = 'show_toast'
export const HIDE_TOAST = 'hide_toast'
export const MACHINE_SUBSCRIBE = 'machine_subscribe'
export const MACHINE_UNSUBSCRIBE = 'machine_unsubscribe'
export const LOAD_SAVE = 'load_save'
